import { COLORS, SHADOWS, RADIUS } from '@shared/config';

export const emptyStyles = {
  container: {
    backgroundColor: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: RADIUS.xl,
    padding: '36px 20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '16px',
    textAlign: 'center',
    boxShadow: SHADOWS.sm,
    width: '100%',
    minHeight: '280px',
    position: 'relative',
    overflow: 'hidden',
    minWidth: 0,
    boxSizing: 'border-box',
  },

  artWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '80px',
    height: '80px',
    backgroundColor: 'rgba(255, 107, 53, 0.05)',
    borderRadius: '50%',
    marginBottom: '4px',
    flexShrink: 0,
  },

  sparkleContainer: {
    position: 'absolute',
    top: '-8px',
    right: '-8px',
    backgroundColor: COLORS.surface,
    borderRadius: '50%',
    padding: '8px',
    display: 'flex',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
  },

  title: {
    margin: 0,
    fontSize: '1.25rem',
    fontWeight: '900',
    color: COLORS.charcoalBlue,
    letterSpacing: '-0.01em',
    lineHeight: 1.2,
  },

  text: {
    margin: 0,
    fontSize: '0.9rem',
    color: COLORS.textSecondary,
    lineHeight: 1.5,
    maxWidth: '280px',
    fontWeight: '500',
  },

  cta: {
    marginTop: '4px',
    backgroundColor: COLORS.atomicTangerine,
    color: 'white',
    border: 'none',
    borderRadius: RADIUS.full,
    padding: '12px 28px',
    fontSize: '0.9rem',
    fontWeight: '800',
    cursor: 'pointer',
    boxShadow: `0 8px 20px ${COLORS.atomicTangerine}40, inset 0 -2px 0 rgba(0,0,0,0.1)`,
    minHeight: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    flexShrink: 0,
  },
};
