import { COLORS, RADIUS, SHADOWS, TRANSITIONS } from '@shared/config';

export const styles = {
  shell: {
    display: 'grid',
    gridTemplateColumns: 'minmax(180px, 0.95fr) minmax(0, 2fr)',
    gap: '8px',
    width: '100%',
    alignItems: 'stretch',
  },
  heroCard: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: '108px',
    padding: '12px 14px',
    borderRadius: RADIUS.lg,
    border: `1px solid ${COLORS.border}`,
    backgroundColor: '#FFF7F3',
    boxShadow: SHADOWS.sm,
  },
  heroLabel: {
    fontSize: '0.72rem',
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: COLORS.textSecondary,
  },
  heroValue: {
    fontSize: 'clamp(1.9rem, 3.2vw, 2.4rem)',
    fontWeight: 900,
    color: COLORS.atomicTangerine,
    lineHeight: 1,
    letterSpacing: '-0.03em',
  },
  secondaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(105px, 1fr))',
    gap: '6px',
  },
  compactContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(112px, 1fr))',
    alignItems: 'stretch',
    gap: '8px',
    padding: '12px 0',
    width: '100%',
  },
  pill: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '62px',
    minWidth: 0,
    padding: '8px 10px',
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    boxShadow: SHADOWS.sm,
    position: 'relative',
    transition: TRANSITIONS.normal,
  },
  value: {
    fontSize: '1.28rem',
    fontWeight: '900',
    color: COLORS.charcoalBlue,
    lineHeight: 1,
    letterSpacing: '-0.015em',
  },
  label: {
    fontSize: '0.64rem',
    fontWeight: '700',
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    marginTop: '4px',
    textAlign: 'center',
  },
};
