import { COLORS, SHADOWS, RADIUS, GLASS, Z_INDEX, SPACING, TRANSITIONS, FONTS } from '@shared/config';

export const styles = {
  container: {
    position: 'fixed',
    bottom: SPACING.xl,
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: Z_INDEX.toast,
    display: 'flex',
    alignItems: 'center',
    gap: SPACING.md,
    padding: `${SPACING.sm} ${SPACING.md}`,
    minWidth: 'min(90vw, 400px)',
    ...GLASS.medium,
    borderRadius: RADIUS.full,
    border: `1px solid ${COLORS.border}`,
    boxShadow: SHADOWS.float,
    overflow: 'hidden',
  },
  content: {
    display: 'flex',
    alignItems: 'center',
    gap: SPACING.sm,
    flex: 1,
  },
  iconWrapper: {
    width: '32px',
    height: '32px',
    borderRadius: RADIUS.full,
    background: `${COLORS.atomicTangerine}15`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: COLORS.atomicTangerine,
  },
  text: {
    fontFamily: FONTS.body,
    fontSize: '0.9rem',
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  updateBtn: {
    background: COLORS.atomicTangerine,
    color: '#fff',
    border: 'none',
    borderRadius: RADIUS.full,
    padding: '8px 16px',
    fontSize: '0.85rem',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: `0 4px 12px ${COLORS.atomicTangerine}30`,
    transition: TRANSITIONS.normal,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  laterBtn: {
    background: 'transparent',
    color: COLORS.textSecondary,
    border: 'none',
    borderRadius: RADIUS.full,
    padding: '8px 12px',
    fontSize: '0.85rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: TRANSITIONS.normal,
  },
  // Adaptaciones mobile
  containerMobile: {
    bottom: '80px', // Por encima de la bottom bar
    width: 'calc(100% - 32px)',
    borderRadius: RADIUS.lg,
    flexDirection: 'column',
    alignItems: 'stretch',
    padding: SPACING.md,
    gap: SPACING.md,
  },
  actionsMobile: {
    justifyContent: 'flex-end',
    width: '100%',
  }
};
